warnings_are_errors: false
os:
  - linux
  - osx
dist: xenial   # required for Python >= 3.7
matrix:
  allow_failures:
    - os: osx
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - pytest
  - pytest --cov-report term --cov=educalingoDictionary tests/

# Push the results back to codecov
after_success:
- codecov
